memlat: Fix perf_event_read_local invocation
This error was introduced with the commit 6e5e3fd

Fixes Error:
../drivers/devfreq/arm-memlat-mon.c:110:67: error: too few arguments to function call, expected 4, have 2
  110 |         if (!event->pevent || perf_event_read_local(event->pevent, &total))
      |                               ~~~~~~~~~~~~~~~~~~~~~                      ^
../include/linux/perf_event.h:918:5: note: 'perf_event_read_local' declared here
  918 | int perf_event_read_local(struct perf_event *event, u64 *value,
      |     ^                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  919 |                           u64 *enabled, u64 *running);
      |                           ~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: RoHaNRaJ <reaPeR10x10x@gmail.com>
Signed-off-by: One4Lots <sahorkot.ontime@gmail.com>